/**
 * Stable, machine-readable error codes. Clients branch on `error.code`, never on `message`, so codes are
 * part of the API contract: add new ones freely, never rename or reuse one.
 */
export const ErrorCode = {
  // ---- request
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  BAD_REQUEST: 'BAD_REQUEST',
  MALFORMED_JSON: 'MALFORMED_JSON',
  FORBIDDEN_JSON_KEY: 'FORBIDDEN_JSON_KEY',
  PAYLOAD_TOO_LARGE: 'PAYLOAD_TOO_LARGE',
  UNSUPPORTED_MEDIA_TYPE: 'UNSUPPORTED_MEDIA_TYPE',
  ROUTE_NOT_FOUND: 'ROUTE_NOT_FOUND',
  METHOD_NOT_ALLOWED: 'METHOD_NOT_ALLOWED',
  RATE_LIMITED: 'RATE_LIMITED',

  // ---- authentication & authorization
  UNAUTHORIZED: 'UNAUTHORIZED',
  INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
  SESSION_EXPIRED: 'SESSION_EXPIRED',
  INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
  REFRESH_TOKEN_REUSED: 'REFRESH_TOKEN_REUSED',
  INVALID_API_KEY: 'INVALID_API_KEY',
  CSRF_TOKEN_INVALID: 'CSRF_TOKEN_INVALID',
  SIGNUP_DISABLED: 'SIGNUP_DISABLED',
  FORBIDDEN: 'FORBIDDEN',
  INSUFFICIENT_ROLE: 'INSUFFICIENT_ROLE',

  // ---- resources
  NOT_FOUND: 'NOT_FOUND',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  API_KEY_NOT_FOUND: 'API_KEY_NOT_FOUND',
  RUN_NOT_FOUND: 'RUN_NOT_FOUND',
  CAPABILITY_NOT_FOUND: 'CAPABILITY_NOT_FOUND',
  TENANT_NOT_FOUND: 'TENANT_NOT_FOUND',
  DATASET_NOT_FOUND: 'DATASET_NOT_FOUND',
  EVAL_NOT_FOUND: 'EVAL_NOT_FOUND',
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  INTERVENTION_NOT_FOUND: 'INTERVENTION_NOT_FOUND',

  // ---- business rules
  CONFLICT: 'CONFLICT',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',
  LAST_ADMIN: 'LAST_ADMIN',
  SELF_MODIFICATION_FORBIDDEN: 'SELF_MODIFICATION_FORBIDDEN',
  INVALID_PASSWORD: 'INVALID_PASSWORD',
  ROLE_EXCEEDS_OWNER: 'ROLE_EXCEEDS_OWNER',
  SELF_APPROVAL_FORBIDDEN: 'SELF_APPROVAL_FORBIDDEN',
  CAPABILITY_NOT_APPROVABLE: 'CAPABILITY_NOT_APPROVABLE',
  CAPABILITY_NOT_APPROVED: 'CAPABILITY_NOT_APPROVED',
  INPUT_CONTRACT_VIOLATION: 'INPUT_CONTRACT_VIOLATION',
  RUN_NOT_LIVE: 'RUN_NOT_LIVE',
  LEASE_CONFLICT: 'LEASE_CONFLICT',
  EVAL_ALREADY_RUNNING: 'EVAL_ALREADY_RUNNING',
  FEATURE_DISABLED: 'FEATURE_DISABLED',

  // ---- dependencies
  ENGINE_UNAVAILABLE: 'ENGINE_UNAVAILABLE',
  ENGINE_TIMEOUT: 'ENGINE_TIMEOUT',
  ENGINE_ERROR: 'ENGINE_ERROR',
  UPSTREAM_UNAVAILABLE: 'UPSTREAM_UNAVAILABLE',
  DATABASE_UNAVAILABLE: 'DATABASE_UNAVAILABLE',
  INTERNAL_SERVER_ERROR: 'INTERNAL_SERVER_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
