import { useQuery } from "@tanstack/react-query";
import { ArrowRight, FileCheck2, FlaskConical, Sparkles } from "lucide-react";
import { Link } from "react-router";

import { EmptyState, PageHeader } from "@/components/page-header";
import { RunStatusBadge } from "@/components/status";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { api, type EvidenceIndex } from "@/lib/api";
import { text } from "@/lib/format";

const SECTIONS: [string, string, (name: string) => boolean][] = [
  ["Discovery", "The model accomplishes the goal; the run becomes an artifact.", (n) => n < "03"],
  ["Probing", "Off-happy-path inputs become reviewed business-outcome handlers.", (n) => n >= "03" && n < "10"],
  [
    "Deterministic replay",
    "No model in the loop: success, outcomes, recoveries, failures, a human handoff.",
    (n) => n.startsWith("1"),
  ],
  ["Multi-tenant", "The same artifact on another institution running the same vendor product.", (n) => n.startsWith("2")],
];

function statusOf(result: string): string {
  if (result.startsWith("replay")) return "succeeded";
  return result;
}

export default function EvidencePage() {
  const { data, isLoading } = useQuery({ queryKey: ["evidence"], queryFn: () => api<EvidenceIndex>("/evidence") });
  return (
    <div className="space-y-6">
      <PageHeader
        title="Evidence"
        description="The checked-in demonstration of the end-to-end flow, generated by scripts/make_evidence.py."
      />
      {isLoading ? (
        <Skeleton className="h-64" />
      ) : !data?.runs.length ? (
        <EmptyState icon={<FileCheck2 />} title="No evidence generated">
          Run <code>make evidence</code> (live model) or <code>make evidence-offline</code>.
        </EmptyState>
      ) : (
        <>
          <Alert>
            {data.mode === "live" ? <Sparkles /> : <FlaskConical />}
            <AlertTitle>{data.mode === "live" ? "Live mode" : "Offline mode"}</AlertTitle>
            <AlertDescription>
              {data.mode === "live"
                ? "Discovery and probe classification were performed by the model; everything after ran with no model in the loop."
                : "Discovery and probing were driven by a scripted stand-in for the model. Run `make evidence` with an API key to regenerate from a live run."}
            </AlertDescription>
          </Alert>
          {SECTIONS.map(([title, description, match]) => {
            const runs = data.runs.filter((r) => match(r.name));
            if (!runs.length) return null;
            return (
              <section key={title} className="space-y-3">
                <div>
                  <h2 className="font-medium">{title}</h2>
                  <p className="text-sm text-muted-foreground">{description}</p>
                </div>
                <div className="grid gap-3 md:grid-cols-2">
                  {runs.map((r) => (
                    <Link key={r.name} to={`/runs/${r.name}`} className="group">
                      <Card size="sm" className="h-full transition-colors group-hover:ring-foreground/30">
                        <CardHeader>
                          <CardTitle className="flex items-center justify-between gap-2">
                            <span className="font-mono text-xs">{r.name}</span>
                            <RunStatusBadge status={statusOf(r.result)} />
                          </CardTitle>
                          <CardDescription>{r.shows}</CardDescription>
                        </CardHeader>
                        <CardContent className="flex items-end justify-between gap-2 text-xs text-muted-foreground">
                          <span className="line-clamp-2">
                            {r.outcome
                              ? `Outcome ${text(r.outcome)}`
                              : r.failure
                                ? text(r.failure)
                                : r.outputs
                                  ? Object.entries(r.outputs)
                                      .map(([k, v]) => `${k}=${text(v)}`)
                                      .join(", ")
                                  : r.result}
                          </span>
                          <ArrowRight
                            className="size-4 shrink-0 opacity-0 transition-opacity group-hover:opacity-100"
                            aria-hidden
                          />
                        </CardContent>
                      </Card>
                    </Link>
                  ))}
                </div>
              </section>
            );
          })}
        </>
      )}
    </div>
  );
}
